=== Marvin-Dziedzina/NuhxBoard/schemas/layout.json
{
  "$schema": "http://json-schema.org/draft-07/schema#",
  "title": "Layout",
  "type": "object",
  "required": [
    "Elements",
    "Height",
    "Width"
  ],
  "properties": {
    "Elements": {
      "type": "array",
      "items": {
        "$ref": "#/definitions/BoardElement"
      }
    },
    "Height": {
      "description": "Window height",
      "type": "number",
      "format": "float"
    },
    "Version": {
      "description": "Doesn't do anything",
      "type": [
        "integer",
        "null"
      ],
      "format": "uint8",
      "minimum": 0.0
    },
    "Width": {
      "description": "Window width",
      "type": "number",
      "format": "float"
    }
  },
  "definitions": {
    "BoardElement": {
      "description": "Union for different element types",
      "oneOf": [
        {
          "type": "object",
          "required": [
            "Boundaries",
            "ChangeOnCaps",
            "Id",
            "KeyCodes",
            "ShiftText",
            "Text",
            "TextPosition",
            "__type"
          ],
          "properties": {
            "Boundaries": {
              "type": "array",
              "items": {
                "$ref": "#/definitions/SerializablePoint"
              }
            },
            "ChangeOnCaps": {
              "type": "boolean"
            },
            "Id": {
              "type": "integer",
              "format": "uint32",
              "minimum": 0.0
            },
            "KeyCodes": {
              "type": "array",
              "items": {
                "type": "integer",
                "format": "uint32",
                "minimum": 0.0
              }
            },
            "ShiftText": {
              "type": "string"
            },
            "Text": {
              "type": "string"
            },
            "TextPosition": {
              "$ref": "#/definitions/SerializablePoint"
            },
            "__type": {
              "type": "string",
              "enum": [
                "KeyboardKey"
              ]
            }
          }
        },
        {
          "type": "object",
          "required": [
            "Boundaries",
            "Id",
            "KeyCodes",
            "Text",
            "TextPosition",
            "__type"
          ],
          "properties": {
            "Boundaries": {
              "type": "array",
              "items": {
                "$ref": "#/definitions/SerializablePoint"
              }
            },
            "Id": {
              "type": "integer",
              "format": "uint32",
              "minimum": 0.0
            },
            "KeyCodes": {
              "type": "array",
              "items": {
                "type": "integer",
                "format": "uint32",
                "minimum": 0.0
              }
            },
            "Text": {
              "type": "string"
            },
            "TextPosition": {
              "$ref": "#/definitions/SerializablePoint"
            },
            "__type": {
              "type": "string",
              "enum": [
                "MouseKey"
              ]
            }
          }
        },
        {
          "type": "object",
          "required": [
            "Boundaries",
            "Id",
            "KeyCodes",
            "Text",
            "TextPosition",
            "__type"
          ],
          "properties": {
            "Boundaries": {
              "type": "array",
              "items": {
                "$ref": "#/definitions/SerializablePoint"
              }
            },
            "Id": {
              "type": "integer",
              "format": "uint32",
              "minimum": 0.0
            },
            "KeyCodes": {
              "type": "array",
              "items": {
                "type": "integer",
                "format": "uint32",
                "minimum": 0.0
              }
            },
            "Text": {
              "type": "string"
            },
            "TextPosition": {
              "$ref": "#/definitions/SerializablePoint"
            },
            "__type": {
              "type": "string",
              "enum": [
                "MouseScroll"
              ]
            }
          }
        },
        {
          "type": "object",
          "required": [
            "Id",
            "Location",
            "Radius",
            "__type"
          ],
          "properties": {
            "Id": {
              "type": "integer",
              "format": "uint32",
              "minimum": 0.0
            },
            "Location": {
              "$ref": "#/definitions/SerializablePoint"
            },
            "Radius": {
              "type": "number",
              "format": "float"
            },
            "__type": {
              "type": "string",
              "enum": [
                "MouseSpeedIndicator"
              ]
            }
          }
        }
      ]
    },
    "SerializablePoint": {
      "type": "object",
      "required": [
        "X",
        "Y"
      ],
      "properties": {
        "X": {
          "type": "integer",
          "format": "uint32",
          "minimum": 0.0
        },
        "Y": {
          "type": "integer",
          "format": "uint32",
          "minimum": 0.0
        }
      }
    }
  }
}

=== Marvin-Dziedzina/NuhxBoard/keyboards/Normal/mouseMovement/keyboard.json
{
  "Elements": [
    {
      "__type": "MouseSpeedIndicator",
      "Id": 0,
      "Location": {
        "X": 83,
        "Y": 83
      },
      "Radius": 70
    }
  ],
  "Height": 166,
  "Version": 2,
  "Width": 166,
  "$schema": "https://raw.githubusercontent.com/justDeeevin/NuhxBoard/refs/heads/main/schemas/layout.json"
}
